# Generated by Django 3.1.1 on 2020-09-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=1, max_digits=10)),
                ('long', models.DecimalField(decimal_places=1, max_digits=10)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('second', models.IntegerField()),
            ],
        ),
    ]
