# Generated by Django 3.1.1 on 2020-09-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstime',
            name='lat',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gpstime',
            name='long',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
