# Generated by Django 3.1.1 on 2020-09-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200918_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstime',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gpstime',
            name='long',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
